runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  OPENAI_API_KEY: "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" 